# To update the glmpynet environment use
# conda env update --file environment.yml --prune
# To create glmpynet from scratch use:
# conda env create -f environment.yml
# conda activate glmpynet
name: glmpynet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - pyyaml
  - pybind11
  - pytest
  - pytest-cov
  - pytest-mock
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - twine
  - build