# To update the glmpynet environment use
# conda env update --file environment.yml --prune
# To create glmpynet from scratch use:
# conda env create -f environment.yml
# conda activate glmpynet
name: glmpynet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - bazel
  - gcc>=9.3.0  # or clang>=10.0.0 for macOS
  - openmp
  - eigen
  - numpy
  - pandas
  - scikit-learn
  - pybind11
  - pytest
  - pytest-cov
  - pytest-mock
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - twine
  - build